### ISSUE TITLE
Plugin Doesn't Work, you swapped the title IDs for EUR and USA

### ISSUE THREAD

**Issue by WiiUFunnn** [jacquesCedric/WUPS_dark_mode_plugin#1]
The plugin doesn't work, but I found out what the error is, in the src folder, open the main.c file with Notepad++ or whatever, the values for Wii U Menu Eur and USA are flipped:

This is what they read:
#define WII_U_MENU_TITLE_ID_EUR (0x0005001010040100)
#define WII_U_MENU_TITLE_ID_USA (0x0005001010040200)

This is what they should read:
#define WII_U_MENU_TITLE_ID_EUR (0x0005001010040200)
#define WII_U_MENU_TITLE_ID_USA (0x0005001010040100)

While I recognize the problem, I'm having all sorts of trouble compiling after i made the edit. Suffice to say, I've never really done this kind of compiling before, so if you could edit, compile and upload the newly compiled .mod, I would really appreciate it, as I'm sure others would as well. Thanks!

**Comment by jacquesCedric** [comment]
That's a particularly ridiculous typo by me. However, I did test it on EUR console and don't have any issues with it. I seem to recall at the time of release that people with USA consoles couldn't get it to work but my understanding of the why was limited.

Unfortunately, I've since upgraded my computer and no longer have the setup to compile this. I do recall though that the WUPS Discord is super helpful. You can check it out [here](https://discord.gg/bZ2rep2). A few people there are probably running newer versions of the tools I used to compile and may be able to sort you out. Sorry I can't be more help.
